### ISSUE TITLE
Further performance enhancement in es()

### ISSUE THREAD

**Issue by dmi3kno** [trnnick/TStools#12]
There must be a way to further enhance performance. I will just put here some ideas that we could try:
- "apply" instead of "for", pre-allocation of vectors instead of dynamic addition ("low hanging fruit")
- RcppParallel. new package on CRAN http://www.r-bloggers.com/rcppparallel-getting-r-and-c-to-work-some-more-in-parallel/
- parallel -  for distributing "ZZZ" across threads

**Comment by trnnick** [comment]
For the parallel implementation let's base it on the `parallel' package. It is the same that is used in forecast and MAPA packages - let us not mix how we create the cluster.

**Comment by config-i1** [comment]
1. If you can show, which parts of code with `for` loop can be substituted by `apply`, I'd be grateful. I'm under impression now that we don't have many loops now.
2. Almost all the vectors and matrices in code are pre-allocated. Once again, I'd be grateful if you can point in the "hanging" ones.
3. It is very hard to construct and estimate an Exponential Smoothing model in parallel, because it is a recursive model (next observation depends on the previous). IMO the only part of the current Rcpp code that can be parallelised is function `errorer` that produces 1 to h steps ahead errors from each observation.
4. Parallel for `ZZZ` is a good idea, but I'm not sure what will happen, when `es` is done in the parallel in a bigger task. For example, we want to apply it to a 100 of series in parallel and we have `ZZZ` in parallel as well. My understanding is that it will slow things down. Am I wrong? Any ideas what to do with it?

**Comment by trnnick** [comment]
On 4. I think you would have a switch for that. If someone want to run it across several time series, then it really depends how the loop across series is setup: is it running the series parallel or serial? So I think that if you have a flag for running parallel or not it would be good. The parallel would obviously be across models. In mapa I have 3 options on that: 1) no parallel, 2) parallel with setting up the cluster - this is rather slow if you are going to run it multiple times, 3) parallel with cluster already initialiased - this is quite fast. Perhaps a similar approach would be helpful? - I would argue not top priority though!

**Comment by dmi3kno** [comment]
I meant the last option, of course, @trnnick. User should initialize the cluster before calling the function. Isn't it what `forecast` and `caret` expect as well? Then user will be able to choose whether to loop across series (in the outer loop) or across models (inside the function).

**Comment by config-i1** [comment]
Ok. It makes sense, indeed. Let's see what can be done :)

**Comment by config-i1** [comment]
Now the performance should not be a big issue. Although it will be improved anyway as soon as the core functions (such as CF()) are moved into Rcpp.
